default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: rails
  password: rails

development:
  <<: *default
  database: cad_development

test:
  <<: *default
  database: cad_test
